# Generated by Django 4.2.2 on 2023-06-20 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0014_alter_post_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
